version: '3.9'
services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tienda_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: node_container
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: node app.js
volumes:
  postgres_data:
